- bin/pre_compile
- manifest.yml
This makes the buildpack generate requirements in a standalone way so that we
don't have to:
1. check it in
2. generate it in Jenkins
> Make buildpack generate requirements.txt

- .bandit
- .circleci/config.yml
- docker/ci.sh
- poetry.lock
- pyproject.toml
- server/settings/environments/production.py
Added as a separate tool rather than as a flake8 plugin, as `flake8-bandit` seems to do literally nothing.
[Example output with no errors](https://app.circleci.com/jobs/github/uktrade/legal-basis-api/52/parallel-runs/0/steps/0-114)
[Example output with error](https://app.circleci.com/jobs/github/uktrade/legal-basis-api/51/parallel-runs/0/steps/0-114)
Not sure how useful this actually is, but it seems worth trying out?
> Add Bandit security linter

- poetry.lock
- pyproject.toml
- server/settings/components/common.py
Restricts access to django admin (and only django admin) to a list of known IPs via a comma-separated env var.
> Add django admin IP restriction support

- docs/django.md
- poetry.lock
- pyproject.toml
- server/settings/components/__init__.py
- server/settings/components/common.py
- server/settings/environments/development.py
- server/settings/environments/production.py
`django-environ` is in use on other DIT projects, and seems to have a slightly nicer API and some djangos-specific convenience methods.
> Replace python-decouple with django-environ

- .circleci/config.yml
- Makefile
- docker/ci.sh
- poetry.lock
- pyproject.toml
- server/apps/main/apps.py
- server/apps/main/middleware.py
- server/settings/components/common.py
- setup.cfg
- tests/test_apps/test_main/test_middleware/test_audit_log_middleware.py
Logs all `LegalBasis.save()` operations via [Django Activity Stream](https://django-activity-stream.readthedocs.io/en/latest/) as `actor verb object [target]` constructs, where `actor` is a Django User instance and `object` and optional `target` are `LegalBasis` instances, e.g:
```
<User pk=1> "created" <LegalBasis pk=1>
<User pk=1> "updated" <LegalBasis pk=1>
<User pk=1> "deleted" <LegalBasis pk=1>
<User pk=1> "added" <Consent pk=1> to <LegalBasis pk=1>
<User pk=1> "removed" <Consent pk=1> from <LegalBasis pk=1>
<User pk=1> "cleared consents" of <LegalBasis pk=1>
```
> Add AuditLogMiddleware

- poetry.lock
- pyproject.toml
- server/settings/components/common.py
Removed in favour of DIT’s nginx ip filter: https://github.com/uktrade/cf-nginx-ip-filter
> Remove django-admin-ip-restrictor

- server/settings/components/drf.py
Change DEFAULT_PERMISSION_CLASSES to `DjangoModelPermissions` from
`DjangoModelPermissionsOrAnonReadOnly`
> Disallow anonymous read access to API

- manifest.yml
Now aligns with the general pattern of specifying one application only rather than one per env, and not specifying routes, services or env vars.
> Fix manifest.yml for Jenkins pipeline

- Procfile
Currently deployed in dev env with 1 worker instance and 256M RAM limit.
> Add formsapi_poller worker process

- server/apps/api/serializers.py
- server/apps/api/views/legal_basis.py
- server/apps/main/migrations/0003_consent_initial_data.py
- server/settings/components/common.py
- tests/test_apps/test_poller/test_managment_commands/test_poll_maxemail.py
- adds API endpoint to return flattened consent data instead of Consent objects nested in LegalBasis objects
- adds initial Consent objects data migration, derived from `settings.CONSENT_TYPES`
- update `TestMaxemailCommand` to account for initial Consent data
> Add API endpoint for data workspace export

- server/apps/api/serializers.py
This is not a valid state and should be prevented to avoid internal server
errors when the validation is enforced at the database constraint level
> Validate that both `email` and `phone` cannot be supplied

- poetry.lock
- pyproject.toml
- server/apps/main/management/commands/example.csv
- server/apps/main/management/commands/import_email_consent.py
New management command called `import_email_consent` that allows importing the
existing records from other systems. Built to handle the transition of consent
data from data hub to this system but can be used for any other imports too.
> Import CSV Consent Management Command

- docker/django/Dockerfile
This commit makes `docker build -f ./docker/django/Dockerfile -t legal_basis`
work again, as it stopped working since we deleted the `docker-entrypoint.sh`
script.
> Docker: Fix docker file to remove COPY of deleted script

- README.md
This adds the quay.io status badge to the README so people know if the docker
build successfully builds.
> Add Quay.io badge

- server/settings/components/common.py
I erred - APM is now running on 443, so no port required
> Remove port from APM URL

- server/settings/environments/default.py
As CF enforces https for this header for external requests, it is safe to default it http. Which might be the reason for next and previous links to https within paginated results.
> changing default X_FORWARDED_PROTO to http

- server/apps/api/views/legal_basis.py
- server/apps/main/middleware.py
- tests/test_apps/test_main/test_views/test_legal_basis_viewset.py
This PR is to add appropriate protocol, `http` or `https` depending on the host name. If the host name is internal, then `http` is enforced. Otherwise it defaults to `https`.
> Fix protocol for pagination links

- server/apps/poller/api_client/maxemail.py
- server/apps/poller/management/commands/poll_maxemail.py
- tests/test_apps/test_poller/test_clients/test_maxemail.py
This PR fixes paging while consuming Maxemail API to get recipients data within a list. 
https://docs.maxemail.xtremepush.com/mxm-dev/api/services/list#List-fetchRecipientsData
As per their documentation: `A maximum of 5000 records will be returned. Therefore to retrieve the complete list, the function should be iterated in a loop, with each loop's start being increased by your value for limit, until the start value is greater than the list_total returned.`
I have ran the command locally before and after fix, to make sure the it runs as intended.
> fix paging of maxemail list members

- server/apps/api/views/legal_basis.py
This PR turns email to lower as email is turned to lower case before saving but it doesn't lower the case and check during lookup.
> turn email to lower when during bulk lookup

- poetry.lock
- server/apps/api/views/legal_basis.py
- tests/conftest.py
- tests/test_apps/test_main/test_views/test_legal_basis_viewset.py
This fixes a problem with bulk lookup endpoint where serializer data was read before calling `is_valid`, it also adds a test to make sure the endpoint returns data.
> fix: bulk lookup endpoint 

- server/apps/api/serializers.py
- server/apps/main/permissions.py
- server/settings/components/common.py
- server/settings/components/drf.py
- tests/conftest.py
- tests/test_apps/test_main/test_views/test_hawk_auth.py
- tests/test_apps/test_main/test_views/test_legal_basis_viewset.py
- Protect api endpoints behind model level read/write permissions.
- Adds some tests for hawk auth
Before go live we will need to update the relevant environments to create read/read write permission groups and apply them to the relevant users.
> feat: protect api behind read/write permissions

- tests/test_apps/test_main/test_views/test_legal_basis_viewset.py
Consent name should be "phone" not "phone_marketing" in tests
> fix: bad consent name breaking api tests

- server/settings/components/common.py
Think it's acceptable to just not include this header anywhere. Plus, I'm not convinced this line of code does anything anyway.
> feat: remove x-xss-protection header

- server/settings/components/common.py
Set `AUTHBROKER_USE_USER_ID_GUID` to `True` to allow us to keep using the legacy sso integration
> fix: force django-staff-sso-client to use user id guid

- server/apps/poller/management/commands/poll_formsapi.py
- tests/test_apps/test_poller/test_managment_commands/test_poll_formsapi.py
Previous PR assumed "contact_consent" was a bool when it is a list, this should return true if email consent is given inside this list
> fix: accessing email consent in combined consent

- docker/django/Dockerfile
The Dockerfile wasn't building - suspect some recent requirements changes have caused errors like:
> Requires-Python >=3.8
when building
> build(deps): bump Docker Python to match prod

- server/apps/poller/management/commands/poll_formsapi_rerun.py
- tests/test_apps/test_poller/test_managment_commands/test_poll_formsapi.py
This is to be able to apply the changes from
https://github.com/uktrade/legal-basis-api/pull/134
https://github.com/uktrade/legal-basis-api/pull/133
https://github.com/uktrade/legal-basis-api/pull/131
retrospectively
> feat: management command to apply forms-api consent retrospectively

- server/apps/poller/management/commands/poll_formsapi.py
It's probably not a real phone number, so shouldn't increase the length of the field I suspect.
> feat: avoid exception if phone number is > 128 characters long

- server/apps/admin_export/urls.py
- server/apps/admin_export/views.py
- server/apps/main/admin.py
- server/settings/components/common.py
- server/templates/admin/change_list_csv_export.html
- server/urls.py
Adds a button to the admin legal basis list page. This button allows all legal basis to be exported into a CSV.
> Add export CSV button to admin for all legal basis

- server/apps/admin_export/views.py
Ensure the user is authenticated and a superuser before allowing CSV exports.
> Add authentication for csv export

- manifest.yml
Updates Jenkins build timeout to 6 minutes instead of 3
> Add timeout to manifest

- manifest.yml
- server/settings/components/common.py
- server/settings/environments/production.py
Using SECURE_SSL_REDIRECT causes an infinet redirect loop. This setting is not necessary on paas anyway as all requests are https
> fix: disable ssl redirect as it's not necessary on paas

- server/apps/poller/api_client/dynamics.py
Dynamics poller is currently not running with this error:
`ERR requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbt.crm11.dynamics.comapi', port=443): Max retries exceeded with url: /data/v9.2/msdynmkt_contactpointconsent4s (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb98873550>: Failed to establish a new connection: [Errno -2] Name or service not known'))`
It is evident from the host name appeared above `dbt.crm11.dynamics.comapi` that the `/` that should have been there is missing. As this could have been removed from both code and Vault by mistake.
So this PR fixes it, and add this `/` back in the code. Vault remains as is, without `/`.
> adds missing slash

- server/apps/poller/api_client/activity.py
The previous 'if' statement was intended to check if the 2 ways of recording consent were present in data, but this was working incorrectly and only checking 'if "email_consent"' which should default to True.
> fix: only process hits with email consent given
